id: P010755
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5318
  title: འདས་ལོག་མ་ཚུལ་ཁྲིམས་དབང་མོའི་རྣམ་ཐར།
  author: ''
  volumes:
    6d1b916c26be41d0a91f7e3eda70f8d1:
      image_group_id: I3CN5320
      title: ''
      volume_number: 1
      total_pages: 210
